-- PROPOSAL ONLY — NOT A MIGRATION.
-- Materialize only through an official file generated by:
--   supabase migration new seed_carb_cycle_phase_templates
--
-- Scope is limited to the confirmed spreadsheet-derived baselines for
-- phases 1, 2 and 3. Phases 4, 5 and 6 are intentionally absent.
-- This proposal does not map phases to protocol stages and does not
-- automate progression between phases.

insert into public.method_configuration_templates (
  template_key,
  domain_key,
  config_schema_key,
  display_name,
  description,
  created_by_kind,
  created_by_profile_id
)
values
  ('nutrition.carb_cycle.phase_1','nutrition','carb_cycle_v1','Carb Cycle — Fase 1','Baseline versionado da Fase 1 confirmada.','system',null),
  ('nutrition.carb_cycle.phase_2','nutrition','carb_cycle_v1','Carb Cycle — Fase 2','Baseline versionado da Fase 2 confirmada.','system',null),
  ('nutrition.carb_cycle.phase_3','nutrition','carb_cycle_v1','Carb Cycle — Fase 3','Baseline versionado da Fase 3 confirmada.','system',null);

insert into public.method_configuration_versions (
  template_id, version_number, schema_version, configuration,
  source_kind, source_reference, created_by_kind, created_by_profile_id,
  activated_at, activated_by_profile_id
)
select
  t.id,
  1,
  1,
  case t.template_key
    when 'nutrition.carb_cycle.phase_1' then
      '{"phaseKey":"phase_1","steps":[{"key":"low_1","label":"Low 1","carbohydratePerKg":{"value":1.55,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"low_2","label":"Low 2","carbohydratePerKg":{"value":1.55,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"high","label":"High","carbohydratePerKg":{"value":4.4,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}}],"linearAverageStepKeys":["low_1","low_2","high"]}'::jsonb
    when 'nutrition.carb_cycle.phase_2' then
      '{"phaseKey":"phase_2","steps":[{"key":"low_1","label":"Low 1","carbohydratePerKg":{"value":1.25,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"low_2","label":"Low 2","carbohydratePerKg":{"value":1.25,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"high","label":"High","carbohydratePerKg":{"value":3.5,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}}],"linearAverageStepKeys":["low_1","low_2","high"]}'::jsonb
    when 'nutrition.carb_cycle.phase_3' then
      '{"phaseKey":"phase_3","steps":[{"key":"low_1","label":"Low 1","carbohydratePerKg":{"value":0.95,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"low_2","label":"Low 2","carbohydratePerKg":{"value":0.95,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"high","label":"High","carbohydratePerKg":{"value":2.6,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}}],"linearAverageStepKeys":["low_1","low_2","high"]}'::jsonb
  end,
  'system_baseline',
  'spreadsheet-derived-confirmed-baseline-2026-10-02',
  'system',
  null,
  now(),
  null
from public.method_configuration_templates t
where t.template_key in (
  'nutrition.carb_cycle.phase_1',
  'nutrition.carb_cycle.phase_2',
  'nutrition.carb_cycle.phase_3'
);
