-- Official migration filename generated by Supabase CLI:
-- supabase migration new harden_snapshot_consumers
-- Generated filename: 20261002231111_harden_snapshot_consumers.sql
--
-- Purpose:
-- 1. close the temporary rollout window after application consumers switched
--    to atomic method-snapshot persistence boundaries;
-- 2. prevent authenticated clients/admins from bypassing those boundaries with
--    direct writes;
-- 3. preserve all historical finalized assessments/liquid events that predate
--    snapshot adoption.
--
-- Existing historical rows are not rewritten.

revoke insert on table public.client_liquid_intake_events from authenticated;

revoke update on table public.client_assessments from authenticated;
grant update (assessed_at, assessment_kind)
  on table public.client_assessments
  to authenticated;

create or replace function public.enforce_client_assessment_lifecycle()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  if old.finalized_at is not null then
    raise exception 'finalized assessment is immutable'
      using errcode = '55000';
  end if;

  if new.client_id is distinct from old.client_id
     or new.created_at is distinct from old.created_at
     or new.created_by_profile_id is distinct from old.created_by_profile_id then
    raise exception 'assessment identity fields are immutable'
      using errcode = '55000';
  end if;

  if new.finalized_at is null
     and new.method_configuration_snapshot_set_id is not null then
    raise exception 'draft assessment cannot reference a method snapshot'
      using errcode = '55000';
  end if;

  if new.finalized_at is null and new.finalized_by_profile_id is not null then
    raise exception 'finalization actor requires finalized_at'
      using errcode = '23514';
  end if;

  if new.finalized_at is not null and new.finalized_by_profile_id is null then
    raise exception 'finalized assessment requires finalization actor'
      using errcode = '23514';
  end if;

  if old.finalized_at is null and new.finalized_at is not null then
    if new.method_configuration_snapshot_set_id is null then
      raise exception 'new assessment finalization requires a method snapshot'
        using errcode = '23514';
    end if;

    new.finalized_at := now();
  end if;

  return new;
end;
$$;

revoke execute on function public.enforce_client_assessment_lifecycle()
  from public, anon, authenticated;
