-- Official migration filename generated by Supabase CLI:
-- supabase migration new snapshot_assessment_and_liquid_consumers
-- Generated filename: 20261002224033_snapshot_assessment_and_liquid_consumers.sql
--
-- Purpose:
-- 1. add explicit snapshot-set FKs to assessment finalizations and liquid events;
-- 2. add atomic, server-only persistence boundaries that create the snapshot and
--    domain fact together;
-- 3. preserve existing historical rows and the current authenticated write paths
--    until consumers are switched in a separate deploy;
-- 4. avoid a production gap where the DB requires snapshots before the app can
--    write through the new boundaries.
--
-- A follow-up hardening migration may require non-null snapshots for new writes
-- only after the application consumers have been deployed and verified.

alter table public.client_assessments
  add column method_configuration_snapshot_set_id uuid;

alter table public.client_assessments
  add constraint client_assessments_snapshot_set_client_fkey
  foreign key (method_configuration_snapshot_set_id, client_id)
  references public.method_configuration_snapshot_sets (id, client_id)
  on delete restrict;

create unique index client_assessments_snapshot_set_unique_idx
  on public.client_assessments (method_configuration_snapshot_set_id)
  where method_configuration_snapshot_set_id is not null;

alter table public.client_liquid_intake_events
  add column method_configuration_snapshot_set_id uuid;

alter table public.client_liquid_intake_events
  add constraint client_liquid_events_snapshot_set_client_fkey
  foreign key (method_configuration_snapshot_set_id, client_id)
  references public.method_configuration_snapshot_sets (id, client_id)
  on delete restrict;

create unique index client_liquid_events_snapshot_set_unique_idx
  on public.client_liquid_intake_events (method_configuration_snapshot_set_id)
  where method_configuration_snapshot_set_id is not null;

create function public.finalize_assessment_from_method_snapshot(
  p_assessment_id uuid,
  p_finalized_by_profile_id uuid,
  p_catalog_template_version_id uuid,
  p_catalog_configuration jsonb,
  p_catalog_result_values jsonb,
  p_definition_template_version_id uuid,
  p_definition_configuration jsonb,
  p_definition_result_values jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = pg_catalog
as $$
declare
  v_assessment public.client_assessments%rowtype;
  v_catalog_template_id uuid;
  v_catalog_template_key text;
  v_definition_template_id uuid;
  v_definition_template_key text;
  v_snapshot_set_id uuid;
  v_catalog_historical_code text;
  v_catalog_semantic_key text;
  v_definition_kind_key text;
  v_can_finalize boolean;
begin
  select *
  into v_assessment
  from public.client_assessments
  where id = p_assessment_id
  for update;

  if not found then
    raise exception 'assessment not found'
      using errcode = '22023';
  end if;

  if v_assessment.finalized_at is not null then
    raise exception 'assessment is already finalized'
      using errcode = '55000';
  end if;

  if v_assessment.method_configuration_snapshot_set_id is not null then
    raise exception 'draft assessment already has a method snapshot'
      using errcode = '55000';
  end if;

  if not exists (
    select 1
    from public.user_roles ur
    join public.client_assignments ca
      on ca.staff_profile_id = ur.profile_id
     and ca.client_id = v_assessment.client_id
     and ca.ended_at is null
    where ur.profile_id = p_finalized_by_profile_id
      and ur.role = 'admin'
  ) then
    raise exception 'active admin assignment is required for assessment finalization'
      using errcode = '42501';
  end if;

  if jsonb_typeof(p_catalog_configuration) is distinct from 'object'
     or jsonb_typeof(p_catalog_result_values) is distinct from 'object'
     or jsonb_typeof(p_definition_configuration) is distinct from 'object'
     or jsonb_typeof(p_definition_result_values) is distinct from 'object' then
    raise exception 'assessment snapshot payloads must be objects'
      using errcode = '22023';
  end if;

  select v.template_id, t.template_key
  into v_catalog_template_id, v_catalog_template_key
  from public.method_configuration_versions v
  join public.method_configuration_templates t on t.id = v.template_id
  where v.id = p_catalog_template_version_id
    and v.activated_at is not null
    and v.retired_at is null;

  if not found
     or v_catalog_template_key <> 'evaluation.assessment_kind_catalog' then
    raise exception 'active assessment kind catalog version is required'
      using errcode = '22023';
  end if;

  select v.template_id, t.template_key
  into v_definition_template_id, v_definition_template_key
  from public.method_configuration_versions v
  join public.method_configuration_templates t on t.id = v.template_id
  where v.id = p_definition_template_version_id
    and v.activated_at is not null
    and v.retired_at is null;

  if not found
     or v_definition_template_key not in (
       'evaluation.assessment_definition.basic',
       'evaluation.assessment_definition.complete'
     ) then
    raise exception 'active assessment definition version is required'
      using errcode = '22023';
  end if;

  v_catalog_historical_code :=
    p_catalog_result_values #>> '{historical_code}';
  v_catalog_semantic_key :=
    p_catalog_result_values #>> '{semantic_key}';
  v_definition_kind_key :=
    p_definition_result_values #>> '{kind_key}';

  begin
    v_can_finalize :=
      (p_definition_result_values #>> '{can_finalize}')::boolean;
  exception
    when others then
      raise exception 'assessment definition result must include boolean can_finalize'
        using errcode = '22023';
  end;

  if v_catalog_historical_code is distinct from v_assessment.assessment_kind then
    raise exception 'assessment kind does not match catalog snapshot result'
      using errcode = '22023';
  end if;

  if v_catalog_semantic_key is null
     or v_definition_kind_key is distinct from v_catalog_semantic_key then
    raise exception 'assessment definition does not match catalog semantic kind'
      using errcode = '22023';
  end if;

  if v_definition_template_key is distinct from
       'evaluation.assessment_definition.' || v_catalog_semantic_key then
    raise exception 'assessment definition template does not match semantic kind'
      using errcode = '22023';
  end if;

  if v_can_finalize is distinct from true then
    raise exception 'assessment configuration does not permit finalization'
      using errcode = '22023';
  end if;

  insert into public.method_configuration_snapshot_sets (
    client_id,
    engine_contract_version,
    created_by_profile_id
  )
  values (
    v_assessment.client_id,
    1,
    p_finalized_by_profile_id
  )
  returning id into v_snapshot_set_id;

  insert into public.method_configuration_snapshots (
    snapshot_set_id,
    client_id,
    template_id,
    template_version_id,
    template_key,
    input_values,
    resolved_configuration,
    result_values
  )
  values
    (
      v_snapshot_set_id,
      v_assessment.client_id,
      v_catalog_template_id,
      p_catalog_template_version_id,
      v_catalog_template_key,
      jsonb_build_object(
        'assessment_kind',
        v_assessment.assessment_kind
      ),
      p_catalog_configuration,
      p_catalog_result_values
    ),
    (
      v_snapshot_set_id,
      v_assessment.client_id,
      v_definition_template_id,
      p_definition_template_version_id,
      v_definition_template_key,
      jsonb_build_object(
        'assessment_id',
        v_assessment.id
      ),
      p_definition_configuration,
      p_definition_result_values
    );

  update public.client_assessments
  set
    method_configuration_snapshot_set_id = v_snapshot_set_id,
    finalized_by_profile_id = p_finalized_by_profile_id,
    finalized_at = now()
  where id = v_assessment.id
    and finalized_at is null;

  if not found then
    raise exception 'assessment finalization lost its draft state'
      using errcode = '55000';
  end if;

  return v_snapshot_set_id;
end;
$$;

revoke execute on function public.finalize_assessment_from_method_snapshot(
  uuid,
  uuid,
  uuid,
  jsonb,
  jsonb,
  uuid,
  jsonb,
  jsonb
) from public, anon, authenticated;

grant execute on function public.finalize_assessment_from_method_snapshot(
  uuid,
  uuid,
  uuid,
  jsonb,
  jsonb,
  uuid,
  jsonb,
  jsonb
) to service_role;

create function public.create_liquid_intake_event_from_method_snapshot(
  p_client_id uuid,
  p_recorded_by_profile_id uuid,
  p_amount_ml integer,
  p_liquid_kind text,
  p_template_version_id uuid,
  p_resolved_configuration jsonb,
  p_result_values jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = pg_catalog
as $$
declare
  v_template_id uuid;
  v_template_key text;
  v_snapshot_set_id uuid;
  v_event_id uuid;
  v_result_kind text;
begin
  if p_amount_ml is null or p_amount_ml <= 0 then
    raise exception 'liquid amount must be positive'
      using errcode = '22023';
  end if;

  if p_liquid_kind is null or length(trim(p_liquid_kind)) = 0 then
    raise exception 'liquid kind is required'
      using errcode = '22023';
  end if;

  if jsonb_typeof(p_resolved_configuration) is distinct from 'object'
     or jsonb_typeof(p_result_values) is distinct from 'object' then
    raise exception 'liquid snapshot payloads must be objects'
      using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.clients c
    join public.user_roles ur
      on ur.profile_id = c.profile_id
     and ur.role = 'client'
    where c.id = p_client_id
      and c.profile_id = p_recorded_by_profile_id
  ) then
    raise exception 'liquid event actor must own the client'
      using errcode = '42501';
  end if;

  select v.template_id, t.template_key
  into v_template_id, v_template_key
  from public.method_configuration_versions v
  join public.method_configuration_templates t on t.id = v.template_id
  where v.id = p_template_version_id
    and v.activated_at is not null
    and v.retired_at is null;

  if not found or v_template_key <> 'hydration.liquid_taxonomy' then
    raise exception 'active liquid taxonomy version is required'
      using errcode = '22023';
  end if;

  v_result_kind := p_result_values #>> '{liquid_kind}';

  if v_result_kind is distinct from p_liquid_kind then
    raise exception 'liquid snapshot result does not match selected kind'
      using errcode = '22023';
  end if;

  if not exists (
    select 1
    from jsonb_array_elements(p_resolved_configuration->'kinds') kind
    where kind #>> '{}' is not null
      and kind->>'key' = p_liquid_kind
  ) then
    raise exception 'selected liquid kind is absent from resolved taxonomy'
      using errcode = '22023';
  end if;

  insert into public.method_configuration_snapshot_sets (
    client_id,
    engine_contract_version,
    created_by_profile_id
  )
  values (
    p_client_id,
    1,
    p_recorded_by_profile_id
  )
  returning id into v_snapshot_set_id;

  insert into public.method_configuration_snapshots (
    snapshot_set_id,
    client_id,
    template_id,
    template_version_id,
    template_key,
    input_values,
    resolved_configuration,
    result_values
  )
  values (
    v_snapshot_set_id,
    p_client_id,
    v_template_id,
    p_template_version_id,
    v_template_key,
    jsonb_build_object(
      'amount_ml',
      jsonb_build_object(
        'value', p_amount_ml,
        'unit', 'ml'
      )
    ),
    p_resolved_configuration,
    p_result_values
  );

  insert into public.client_liquid_intake_events (
    client_id,
    recorded_by_profile_id,
    amount_ml,
    liquid_kind,
    method_configuration_snapshot_set_id
  )
  values (
    p_client_id,
    p_recorded_by_profile_id,
    p_amount_ml,
    p_liquid_kind,
    v_snapshot_set_id
  )
  returning id into v_event_id;

  return v_event_id;
end;
$$;

revoke execute on function public.create_liquid_intake_event_from_method_snapshot(
  uuid,
  uuid,
  integer,
  text,
  uuid,
  jsonb,
  jsonb
) from public, anon, authenticated;

grant execute on function public.create_liquid_intake_event_from_method_snapshot(
  uuid,
  uuid,
  integer,
  text,
  uuid,
  jsonb,
  jsonb
) to service_role;
