-- Official migration filename generated by Supabase CLI:
-- supabase migration new hydrate_client_targets_from_configuration
-- Generated filename: 20261002005720_hydrate_client_targets_from_configuration.sql
--
-- Purpose:
-- 1. seed the confirmed hydration target formula as versioned configuration;
-- 2. preserve legacy hydration target rows unchanged;
-- 3. add an explicit snapshot-based path for future configured hydration targets;
-- 4. avoid changing or rewriting the already-applied 20260930132221 migration.

insert into public.method_configuration_templates (
  template_key,
  domain_key,
  config_schema_key,
  display_name,
  description,
  created_by_kind,
  created_by_profile_id
)
values (
  'hydration.daily_target',
  'hydration',
  'method_engine_v1',
  'Meta diaria de liquidos',
  'Template versionado da meta diaria de liquidos baseada no peso corporal.',
  'system',
  null
);

insert into public.method_configuration_versions (
  template_id,
  version_number,
  schema_version,
  configuration,
  source_kind,
  source_reference,
  created_by_kind,
  created_by_profile_id,
  activated_at,
  activated_by_profile_id
)
select
  t.id,
  1,
  1,
  '{
    "inputs": {
      "weight_kg": {
        "unit": "kg"
      }
    },
    "parameters": {
      "daily_ml_per_kg": {
        "value": 60,
        "unit": "ml_per_kg"
      }
    },
    "outputs": {
      "target_ml": {
        "unit": "ml",
        "expression": {
          "op": "round",
          "arg": {
            "op": "multiply",
            "args": [
              {
                "op": "input",
                "key": "weight_kg"
              },
              {
                "op": "parameter",
                "key": "daily_ml_per_kg"
              }
            ]
          }
        }
      }
    }
  }'::jsonb,
  'system_baseline',
  'confirmed-current-template-2026-10-02',
  'system',
  null,
  now(),
  null
from public.method_configuration_templates t
where t.template_key = 'hydration.daily_target';

alter table public.client_hydration_targets
  add column method_configuration_snapshot_set_id uuid,
  add column resolved_target_ml integer;

alter table public.client_hydration_targets
  drop constraint client_hydration_targets_method_key_check;

alter table public.client_hydration_targets
  add constraint client_hydration_targets_method_key_check
  check (
    method_key in (
      'patty_60_ml_per_kg',
      'method_configuration_snapshot'
    )
  );

alter table public.client_hydration_targets
  add constraint client_hydration_targets_resolved_target_positive
  check (
    resolved_target_ml is null
    or resolved_target_ml > 0
  );

alter table public.client_hydration_targets
  add constraint client_hydration_targets_configuration_mode_consistent
  check (
    (
      method_key = 'patty_60_ml_per_kg'
      and method_configuration_snapshot_set_id is null
      and resolved_target_ml is null
    )
    or
    (
      method_key = 'method_configuration_snapshot'
      and method_configuration_snapshot_set_id is not null
      and resolved_target_ml is not null
    )
  );

alter table public.client_hydration_targets
  add constraint client_hydration_targets_snapshot_set_client_fkey
  foreign key (method_configuration_snapshot_set_id, client_id)
  references public.method_configuration_snapshot_sets (id, client_id)
  on delete restrict;

create unique index client_hydration_targets_snapshot_set_unique_idx
  on public.client_hydration_targets (method_configuration_snapshot_set_id)
  where method_configuration_snapshot_set_id is not null;
