-- Official migration filename generated by Supabase CLI:
-- supabase migration new hydrate_client_targets_from_configuration
-- Generated filename: 20261002005720_hydrate_client_targets_from_configuration.sql
--
-- Purpose:
-- 1. seed the confirmed hydration target formula as versioned configuration;
-- 2. preserve legacy hydration target rows unchanged;
-- 3. add an explicit snapshot-based path for future configured hydration targets;
-- 4. avoid changing or rewriting the already-applied 20260930132221 migration.

insert into public.method_configuration_templates (
  template_key,
  domain_key,
  config_schema_key,
  display_name,
  description,
  created_by_kind,
  created_by_profile_id
)
values (
  'hydration.daily_target',
  'hydration',
  'method_engine_v1',
  'Meta diaria de liquidos',
  'Template versionado da meta diaria de liquidos baseada no peso corporal.',
  'system',
  null
);

insert into public.method_configuration_versions (
  template_id,
  version_number,
  schema_version,
  configuration,
  source_kind,
  source_reference,
  created_by_kind,
  created_by_profile_id,
  activated_at,
  activated_by_profile_id
)
select
  t.id,
  1,
  1,
  '{
    "inputs": {
      "weight_kg": {
        "unit": "kg"
      }
    },
    "parameters": {
      "daily_ml_per_kg": {
        "value": 60,
        "unit": "ml_per_kg"
      }
    },
    "outputs": {
      "target_ml": {
        "unit": "ml",
        "expression": {
          "op": "round",
          "arg": {
            "op": "multiply",
            "args": [
              {
                "op": "input",
                "key": "weight_kg"
              },
              {
                "op": "parameter",
                "key": "daily_ml_per_kg"
              }
            ]
          }
        }
      }
    }
  }'::jsonb,
  'system_baseline',
  'confirmed-current-template-2026-10-02',
  'system',
  null,
  now(),
  null
from public.method_configuration_templates t
where t.template_key = 'hydration.daily_target';

alter table public.client_hydration_targets
  add column method_configuration_snapshot_set_id uuid,
  add column resolved_target_ml integer;

alter table public.client_hydration_targets
  drop constraint client_hydration_targets_method_key_check;

alter table public.client_hydration_targets
  add constraint client_hydration_targets_method_key_check
  check (
    method_key in (
      'patty_60_ml_per_kg',
      'method_configuration_snapshot'
    )
  );

alter table public.client_hydration_targets
  add constraint client_hydration_targets_resolved_target_positive
  check (
    resolved_target_ml is null
    or resolved_target_ml > 0
  );

alter table public.client_hydration_targets
  add constraint client_hydration_targets_configuration_mode_consistent
  check (
    (
      method_key = 'patty_60_ml_per_kg'
      and method_configuration_snapshot_set_id is null
      and resolved_target_ml is null
    )
    or
    (
      method_key = 'method_configuration_snapshot'
      and method_configuration_snapshot_set_id is not null
      and resolved_target_ml is not null
    )
  );

alter table public.client_hydration_targets
  add constraint client_hydration_targets_snapshot_set_client_fkey
  foreign key (method_configuration_snapshot_set_id, client_id)
  references public.method_configuration_snapshot_sets (id, client_id)
  on delete restrict;

create unique index client_hydration_targets_snapshot_set_unique_idx
  on public.client_hydration_targets (method_configuration_snapshot_set_id)
  where method_configuration_snapshot_set_id is not null;


create function public.create_hydration_target_from_method_snapshot(
  p_client_id uuid,
  p_created_by_profile_id uuid,
  p_weight_kg numeric,
  p_template_version_id uuid,
  p_resolved_configuration jsonb,
  p_result_values jsonb,
  p_resolved_target_ml integer,
  p_override_version_id uuid default null
)
returns uuid
language plpgsql
security invoker
set search_path = pg_catalog
as $$
declare
  v_template_id uuid;
  v_template_key text;
  v_snapshot_set_id uuid;
  v_snapshot_id uuid;
  v_hydration_target_id uuid;
  v_result_target numeric;
begin
  if p_weight_kg is null or p_weight_kg <= 0 then
    raise exception 'hydration weight must be positive'
      using errcode = '22023';
  end if;

  if p_resolved_target_ml is null or p_resolved_target_ml <= 0 then
    raise exception 'resolved hydration target must be positive'
      using errcode = '22023';
  end if;

  if jsonb_typeof(p_resolved_configuration) is distinct from 'object' then
    raise exception 'resolved hydration configuration must be an object'
      using errcode = '22023';
  end if;

  if jsonb_typeof(p_result_values) is distinct from 'object' then
    raise exception 'hydration result values must be an object'
      using errcode = '22023';
  end if;

  if p_result_values #>> '{target_ml,unit}' is distinct from 'ml' then
    raise exception 'hydration result target_ml must use ml'
      using errcode = '22023';
  end if;

  begin
    v_result_target := (p_result_values #>> '{target_ml,value}')::numeric;
  exception
    when others then
      raise exception 'hydration result target_ml must be numeric'
        using errcode = '22023';
  end;

  if v_result_target is distinct from p_resolved_target_ml::numeric then
    raise exception 'hydration result target_ml does not match resolved target'
      using errcode = '22023';
  end if;

  select
    v.template_id,
    t.template_key
  into
    v_template_id,
    v_template_key
  from public.method_configuration_versions v
  join public.method_configuration_templates t
    on t.id = v.template_id
  where v.id = p_template_version_id
    and v.activated_at is not null
    and v.retired_at is null;

  if not found or v_template_key <> 'hydration.daily_target' then
    raise exception 'active hydration template version is required'
      using errcode = '22023';
  end if;

  if p_override_version_id is not null
     and not exists (
       select 1
       from public.client_method_configuration_override_versions o
       where o.id = p_override_version_id
         and o.client_id = p_client_id
         and o.template_id = v_template_id
         and o.based_on_template_version_id = p_template_version_id
         and o.protocol_version_id is null
         and o.activated_at is not null
         and o.retired_at is null
     ) then
    raise exception 'active client hydration override does not match resolution'
      using errcode = '22023';
  end if;

  insert into public.method_configuration_snapshot_sets (
    client_id,
    engine_contract_version,
    created_by_profile_id
  )
  values (
    p_client_id,
    1,
    p_created_by_profile_id
  )
  returning id into v_snapshot_set_id;

  insert into public.method_configuration_snapshots (
    snapshot_set_id,
    client_id,
    template_id,
    template_version_id,
    template_key,
    input_values,
    resolved_configuration,
    result_values
  )
  values (
    v_snapshot_set_id,
    p_client_id,
    v_template_id,
    p_template_version_id,
    v_template_key,
    jsonb_build_object(
      'weight_kg',
      jsonb_build_object(
        'value', p_weight_kg,
        'unit', 'kg'
      )
    ),
    p_resolved_configuration,
    p_result_values
  )
  returning id into v_snapshot_id;

  if p_override_version_id is not null then
    insert into public.method_configuration_snapshot_overrides (
      snapshot_id,
      client_id,
      template_id,
      template_version_id,
      override_version_id,
      precedence
    )
    values (
      v_snapshot_id,
      p_client_id,
      v_template_id,
      p_template_version_id,
      p_override_version_id,
      1
    );
  end if;

  insert into public.client_hydration_targets (
    client_id,
    weight_kg,
    method_key,
    method_configuration_snapshot_set_id,
    resolved_target_ml,
    created_by_profile_id
  )
  values (
    p_client_id,
    p_weight_kg,
    'method_configuration_snapshot',
    v_snapshot_set_id,
    p_resolved_target_ml,
    p_created_by_profile_id
  )
  returning id into v_hydration_target_id;

  return v_hydration_target_id;
end;
$$;

revoke execute on function public.create_hydration_target_from_method_snapshot(
  uuid,
  uuid,
  numeric,
  uuid,
  jsonb,
  jsonb,
  integer,
  uuid
) from public, anon, authenticated;

grant execute on function public.create_hydration_target_from_method_snapshot(
  uuid,
  uuid,
  numeric,
  uuid,
  jsonb,
  jsonb,
  integer,
  uuid
) to service_role;
