-- Official migration filename generated by Supabase CLI:
-- supabase migration new seed_higher_fat_protein_limit_template
-- Generated filename: 20261001235018_seed_higher_fat_protein_limit_template.sql
--
-- Purpose:
-- move the confirmed higher-fat protein daily limit out of runtime code
-- and into versioned method configuration.
--
-- Current confirmed baseline:
-- maximum higher-fat protein doses = ceil(total protein doses * 0.5)

insert into public.method_configuration_templates (
  template_key,
  domain_key,
  config_schema_key,
  display_name,
  description,
  created_by_kind,
  created_by_profile_id
)
values (
  'nutrition.protein.higher_fat_daily_limit',
  'nutrition',
  'method_engine_v1',
  'Limite diário de proteína com maior teor de gordura',
  'Template versionado para o limite diário do grupo de proteína com maior teor de gordura.',
  'system',
  null
);

insert into public.method_configuration_versions (
  template_id,
  version_number,
  schema_version,
  configuration,
  source_kind,
  source_reference,
  created_by_kind,
  created_by_profile_id,
  activated_at,
  activated_by_profile_id
)
select
  t.id,
  1,
  1,
  '{
    "inputs": {
      "total_protein_doses": {
        "unit": "dose"
      }
    },
    "parameters": {
      "higher_fat_ratio": {
        "value": 0.5,
        "unit": "ratio"
      }
    },
    "outputs": {
      "max_higher_fat_protein_doses": {
        "unit": "dose",
        "expression": {
          "op": "ceil",
          "arg": {
            "op": "multiply",
            "args": [
              {
                "op": "input",
                "key": "total_protein_doses"
              },
              {
                "op": "parameter",
                "key": "higher_fat_ratio"
              }
            ]
          }
        }
      }
    }
  }'::jsonb,
  'system_baseline',
  'confirmed-current-template-2026-10-01',
  'system',
  null,
  now(),
  null
from public.method_configuration_templates t
where t.template_key = 'nutrition.protein.higher_fat_daily_limit';
