-- Official migration filename generated by Supabase CLI:
-- supabase migration new seed_initial_method_templates
-- Generated filename: 20261001230751_seed_initial_method_templates.sql
--
-- Purpose:
-- 1. distinguish system-seeded baseline provenance from human authorship;
-- 2. seed the confirmed current dose and Recognition Metabolic templates;
-- 3. keep professional values in versioned configuration instead of runtime code.

alter table public.method_configuration_templates
  alter column created_by_profile_id drop not null;

alter table public.method_configuration_templates
  add column created_by_kind text not null default 'profile';

alter table public.method_configuration_templates
  add constraint method_configuration_templates_creator_consistent
  check (
    (
      created_by_kind = 'profile'
      and created_by_profile_id is not null
    )
    or
    (
      created_by_kind = 'system'
      and created_by_profile_id is null
    )
  );

alter table public.method_configuration_versions
  alter column created_by_profile_id drop not null;

alter table public.method_configuration_versions
  add column created_by_kind text not null default 'profile';

alter table public.method_configuration_versions
  add constraint method_configuration_versions_creator_consistent
  check (
    (
      created_by_kind = 'profile'
      and created_by_profile_id is not null
      and source_kind <> 'system_baseline'
    )
    or
    (
      created_by_kind = 'system'
      and created_by_profile_id is null
      and source_kind = 'system_baseline'
    )
  );

alter table public.method_configuration_versions
  drop constraint method_configuration_versions_activation_actor_consistent;

alter table public.method_configuration_versions
  add constraint method_configuration_versions_activation_actor_consistent
  check (
    (
      activated_at is null
      and activated_by_profile_id is null
    )
    or
    (
      activated_at is not null
      and (
        activated_by_profile_id is not null
        or (
          created_by_kind = 'system'
          and source_kind = 'system_baseline'
          and activated_by_profile_id is null
        )
      )
    )
  );

create or replace function public.guard_method_configuration_template_identity()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  if new.id is distinct from old.id
     or new.template_key is distinct from old.template_key
     or new.domain_key is distinct from old.domain_key
     or new.config_schema_key is distinct from old.config_schema_key
     or new.created_by_profile_id is distinct from old.created_by_profile_id
     or new.created_by_kind is distinct from old.created_by_kind
     or new.created_at is distinct from old.created_at then
    raise exception 'method configuration template identity is immutable'
      using errcode = '55000';
  end if;

  return new;
end;
$$;

create or replace function public.guard_method_configuration_version_lifecycle()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  if old.retired_at is not null then
    raise exception 'retired method configuration version is immutable'
      using errcode = '55000';
  end if;

  if new.id is distinct from old.id
     or new.template_id is distinct from old.template_id
     or new.version_number is distinct from old.version_number
     or new.created_by_profile_id is distinct from old.created_by_profile_id
     or new.created_by_kind is distinct from old.created_by_kind
     or new.created_at is distinct from old.created_at then
    raise exception 'method configuration version identity is immutable'
      using errcode = '55000';
  end if;

  if old.activated_at is not null then
    if new.schema_version is distinct from old.schema_version
       or new.configuration is distinct from old.configuration
       or new.source_kind is distinct from old.source_kind
       or new.source_reference is distinct from old.source_reference
       or new.activated_at is distinct from old.activated_at
       or new.activated_by_profile_id is distinct from old.activated_by_profile_id then
      raise exception 'active method configuration version content is immutable'
        using errcode = '55000';
    end if;
  end if;

  if old.activated_at is null and new.retired_at is not null then
    raise exception 'method configuration version must be activated before retirement'
      using errcode = '55000';
  end if;

  return new;
end;
$$;

insert into public.method_configuration_templates (
  template_key,
  domain_key,
  config_schema_key,
  display_name,
  description,
  created_by_kind,
  created_by_profile_id
)
values
  (
    'nutrition.dose.protein',
    'nutrition',
    'scalar_parameter_v1',
    'Dose de proteína',
    'Template inicial versionado para gramas por dose de proteína.',
    'system',
    null
  ),
  (
    'nutrition.dose.carbohydrate',
    'nutrition',
    'scalar_parameter_v1',
    'Dose de carboidrato',
    'Template inicial versionado para gramas por dose de carboidrato.',
    'system',
    null
  ),
  (
    'nutrition.dose.fat',
    'nutrition',
    'scalar_parameter_v1',
    'Dose de gordura',
    'Template inicial versionado para gramas por dose de gordura.',
    'system',
    null
  ),
  (
    'nutrition.recognition.macros',
    'nutrition',
    'method_engine_v1',
    'Reconhecimento Metabólico — macros',
    'Template inicial versionado das referências de macros do Reconhecimento Metabólico.',
    'system',
    null
  );

insert into public.method_configuration_versions (
  template_id,
  version_number,
  schema_version,
  configuration,
  source_kind,
  source_reference,
  created_by_kind,
  created_by_profile_id,
  activated_at,
  activated_by_profile_id
)
select
  t.id,
  1,
  1,
  case t.template_key
    when 'nutrition.dose.protein' then
      '{"value":15,"unit":"g_per_dose"}'::jsonb
    when 'nutrition.dose.carbohydrate' then
      '{"value":12,"unit":"g_per_dose"}'::jsonb
    when 'nutrition.dose.fat' then
      '{"value":6,"unit":"g_per_dose"}'::jsonb
    when 'nutrition.recognition.macros' then
      '{
        "inputs": {
          "weight_kg": {
            "unit": "kg"
          }
        },
        "parameters": {
          "protein_per_kg": {
            "value": 2,
            "unit": "g_per_kg"
          },
          "carbohydrate_per_kg": {
            "value": 2,
            "unit": "g_per_kg"
          },
          "fat_daily": {
            "value": 50,
            "unit": "g"
          }
        },
        "outputs": {
          "protein_grams": {
            "unit": "g",
            "expression": {
              "op": "multiply",
              "args": [
                {
                  "op": "input",
                  "key": "weight_kg"
                },
                {
                  "op": "parameter",
                  "key": "protein_per_kg"
                }
              ]
            }
          },
          "carbohydrate_grams": {
            "unit": "g",
            "expression": {
              "op": "multiply",
              "args": [
                {
                  "op": "input",
                  "key": "weight_kg"
                },
                {
                  "op": "parameter",
                  "key": "carbohydrate_per_kg"
                }
              ]
            }
          },
          "fat_grams": {
            "unit": "g",
            "expression": {
              "op": "parameter",
              "key": "fat_daily"
            }
          }
        }
      }'::jsonb
    else
      null
  end,
  'system_baseline',
  'confirmed-current-template-2026-10-01',
  'system',
  null,
  now(),
  null
from public.method_configuration_templates t
where t.template_key in (
  'nutrition.dose.protein',
  'nutrition.dose.carbohydrate',
  'nutrition.dose.fat',
  'nutrition.recognition.macros'
);
