-- Official migration shell filename generated by Supabase CLI on 2026-10-02.\n-- Materializes reviewed Batch A templates only; no consumer switch.\n\ninsert into public.method_configuration_templates (
  template_key,
  domain_key,
  config_schema_key,
  display_name,
  description,
  created_by_kind,
  created_by_profile_id
)
values
  (
    'nutrition.vegetable_carbohydrate_equivalence',
    'nutrition',
    'method_engine_v1',
    'Equivalência de legumes em carboidrato',
    'Template versionado da equivalência confirmada entre doses de legumes e doses de carboidrato.',
    'system',
    null
  ),
  (
    'workflow.anamnesis_clarification_reminder',
    'workflow',
    'scalar_parameter_v1',
    'Intervalo do lembrete de esclarecimento',
    'Template versionado do intervalo confirmado para considerar um lembrete de esclarecimento devido.',
    'system',
    null
  );

insert into public.method_configuration_versions (
  template_id,
  version_number,
  schema_version,
  configuration,
  source_kind,
  source_reference,
  created_by_kind,
  created_by_profile_id,
  activated_at,
  activated_by_profile_id
)
select
  t.id,
  1,
  1,
  case t.template_key
    when 'nutrition.vegetable_carbohydrate_equivalence' then
      '{
        "inputs": {
          "vegetable_doses": {
            "unit": "dose"
          }
        },
        "parameters": {
          "vegetable_doses_per_carbohydrate_dose": {
            "value": 2,
            "unit": "ratio"
          }
        },
        "outputs": {
          "carbohydrate_dose_equivalent": {
            "unit": "dose",
            "expression": {
              "op": "divide",
              "args": [
                {
                  "op": "input",
                  "key": "vegetable_doses"
                },
                {
                  "op": "parameter",
                  "key": "vegetable_doses_per_carbohydrate_dose"
                }
              ]
            }
          }
        }
      }'::jsonb
    when 'workflow.anamnesis_clarification_reminder' then
      '{"value":24,"unit":"hour"}'::jsonb
    else
      null
  end,
  'system_baseline',
  'confirmed-current-template-2026-10-02',
  'system',
  null,
  now(),
  null
from public.method_configuration_templates t
where t.template_key in (
  'nutrition.vegetable_carbohydrate_equivalence',
  'workflow.anamnesis_clarification_reminder'
);
