-- Official migration filename generated by Supabase CLI:
-- supabase migration new seed_method_configuration_batch_b
-- Generated filename: 20261002220812_seed_method_configuration_batch_b.sql
--
-- Scope:
-- 1. confirmed Carb Cycle phase templates 1-3 only;
-- 2. versioned assessment compatibility catalog and Basic/Complete definitions;
-- 3. versioned liquid taxonomy without inventing a minimum pure-water ratio.
--
-- Explicitly out of scope:
-- - Carb Cycle phases 4-6;
-- - automatic mapping/progression between protocol stages and Carb Cycle phases;
-- - assessment cadence/calendar anchor rules;
-- - minimum pure-water ratio.

insert into public.method_configuration_templates (
  template_key,
  domain_key,
  config_schema_key,
  display_name,
  description,
  created_by_kind,
  created_by_profile_id
)
values
  ('nutrition.carb_cycle.phase_1','nutrition','carb_cycle_v1','Carb Cycle — Fase 1','Baseline versionado da Fase 1 confirmada.','system',null),
  ('nutrition.carb_cycle.phase_2','nutrition','carb_cycle_v1','Carb Cycle — Fase 2','Baseline versionado da Fase 2 confirmada.','system',null),
  ('nutrition.carb_cycle.phase_3','nutrition','carb_cycle_v1','Carb Cycle — Fase 3','Baseline versionado da Fase 3 confirmada.','system',null),
  ('evaluation.assessment_kind_catalog','evaluation','assessment_kind_catalog_v1','Catálogo de tipos de avaliação','Compatibilidade versionada entre códigos históricos e tipos semânticos.','system',null),
  ('evaluation.assessment_definition.basic','evaluation','assessment_definition_v1','Definição da Avaliação Básica','Campos obrigatórios confirmados da Avaliação Básica.','system',null),
  ('evaluation.assessment_definition.complete','evaluation','assessment_definition_v1','Definição da Avaliação Completa','Campos obrigatórios confirmados e requisito de foto da Avaliação Completa.','system',null),
  ('hydration.liquid_taxonomy','hydration','liquid_taxonomy_v1','Taxonomia de líquidos','Catálogo versionado dos tipos de líquido elegíveis no check-in.','system',null);

insert into public.method_configuration_versions (
  template_id,
  version_number,
  schema_version,
  configuration,
  source_kind,
  source_reference,
  created_by_kind,
  created_by_profile_id,
  activated_at,
  activated_by_profile_id
)
select
  t.id,
  1,
  1,
  case t.template_key
    when 'nutrition.carb_cycle.phase_1' then
      '{"phaseKey":"phase_1","steps":[{"key":"low_1","label":"Low 1","carbohydratePerKg":{"value":1.55,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"low_2","label":"Low 2","carbohydratePerKg":{"value":1.55,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"high","label":"High","carbohydratePerKg":{"value":4.4,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}}],"linearAverageStepKeys":["low_1","low_2","high"]}'::jsonb
    when 'nutrition.carb_cycle.phase_2' then
      '{"phaseKey":"phase_2","steps":[{"key":"low_1","label":"Low 1","carbohydratePerKg":{"value":1.25,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"low_2","label":"Low 2","carbohydratePerKg":{"value":1.25,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"high","label":"High","carbohydratePerKg":{"value":3.5,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}}],"linearAverageStepKeys":["low_1","low_2","high"]}'::jsonb
    when 'nutrition.carb_cycle.phase_3' then
      '{"phaseKey":"phase_3","steps":[{"key":"low_1","label":"Low 1","carbohydratePerKg":{"value":0.95,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"low_2","label":"Low 2","carbohydratePerKg":{"value":0.95,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}},{"key":"high","label":"High","carbohydratePerKg":{"value":2.6,"unit":"g_per_kg"},"proteinPerKg":{"value":2.3,"unit":"g_per_kg"}}],"linearAverageStepKeys":["low_1","low_2","high"]}'::jsonb
    when 'evaluation.assessment_kind_catalog' then
      '{"entries":[{"historicalCode":"fortnightly","semanticKey":"basic","label":"Básica"},{"historicalCode":"monthly","semanticKey":"complete","label":"Completa"}]}'::jsonb
    when 'evaluation.assessment_definition.basic' then
      '{"kindKey":"basic","requiredMeasurements":[{"key":"peso","label":"Peso","aliases":["weight"]},{"key":"cintura","label":"Cintura","aliases":["waist"]},{"key":"abdomen","label":"Abdômen","aliases":["abdominal","abdômen"]},{"key":"quadril","label":"Quadril","aliases":["hip"]}],"photoRequirement":null}'::jsonb
    when 'evaluation.assessment_definition.complete' then
      '{"kindKey":"complete","requiredMeasurements":[{"key":"peso","label":"Peso","aliases":["weight"]},{"key":"cintura","label":"Cintura","aliases":["waist"]},{"key":"abdomen","label":"Abdômen","aliases":["abdominal","abdômen"]},{"key":"coxa","label":"Coxa direita","aliases":["thigh"]},{"key":"biceps","label":"Bíceps direito","aliases":[]},{"key":"torax","label":"Busto/peito","aliases":["bust","busto","chest","peito"]},{"key":"quadril","label":"Quadril","aliases":["hip"]},{"key":"ombros","label":"Ombros","aliases":["ombro"]},{"key":"panturrilhas","label":"Panturrilha direita","aliases":["panturrilha"]}],"photoRequirement":{"label":"Foto vinculada","minimumCount":1}}'::jsonb
    when 'hydration.liquid_taxonomy' then
      '{"kinds":[{"key":"water","label":"Água pura","hydrationClass":"pure_water"},{"key":"zero_calorie_other","label":"Outro líquido zero calorias","hydrationClass":"zero_calorie_other"}]}'::jsonb
  end,
  'system_baseline',
  case
    when t.template_key like 'nutrition.carb_cycle.phase_%'
      then 'spreadsheet-derived-confirmed-baseline-2026-10-02'
    when t.template_key like 'evaluation.%'
      then 'confirmed-assessment-baseline-2026-10-02'
    when t.template_key = 'hydration.liquid_taxonomy'
      then 'confirmed-liquid-taxonomy-baseline-2026-10-02'
  end,
  'system',
  null,
  now(),
  null
from public.method_configuration_templates t
where t.template_key in (
  'nutrition.carb_cycle.phase_1',
  'nutrition.carb_cycle.phase_2',
  'nutrition.carb_cycle.phase_3',
  'evaluation.assessment_kind_catalog',
  'evaluation.assessment_definition.basic',
  'evaluation.assessment_definition.complete',
  'hydration.liquid_taxonomy'
);
